CREATE TABLE PRODUCT(productId INT PRIMARY KEY, name VARCHAR(255));
CREATE TABLE BRAND(brandId INT PRIMARY KEY, name VARCHAR(255));
CREATE TABLE PRICES(productId INT NOT NULL, brandId INT NOT NULL,  start_date TIMESTAMP NULL,end_date TIMESTAMP NULL, price_list INT NOT NULL, priority INT NOT NULL,  price DECIMAL(16,2) NOT NULL, curr VARCHAR(10) NOT NULL, CONSTRAINT fk_PRICES_BRAND1
                                                                                                                                                                                                                                                                FOREIGN KEY (brandId)
                                                                                                                                                                                                                                                                REFERENCES BRAND (brandId)
                                                                                                                                                                                                                                                                ON DELETE NO ACTION
                                                                                                                                                                                                                                                                ON UPDATE NO ACTION,   CONSTRAINT fk_PRICES_PRODUCT1
                                                                                                                                                                                                                                                                                              FOREIGN KEY (productId)
                                                                                                                                                                                                                                                                                              REFERENCES PRODUCT (productId)
                                                                                                                                                                                                                                                                                              ON DELETE NO ACTION
                                                                                                                                                                                                                                                                                              ON UPDATE NO ACTION);

